name: Build Renkulab Menu Extension

on:
  push:
    branches: master
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '10.x'
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install dependencies
      run: python -m pip install jupyterlab
    - name: Build the extension
      run: |
        cd renkulab_menu_extension

        jlpm
        jlpm run eslint:check

        jupyter labextension install .

        python -m jupyterlab.browser_check
